services:

# to-do: setup audiobookshelf oidc

################################################################################
##### audiobookshelf
################################################################################

  audiobookshelf:
    container_name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf:latest
    pull_policy: always
    restart: unless-stopped
    networks:
      - main
#   ports:
#     - ${AUDIOBOOKSHELF__PORT_EXT}:${AUDIOBOOKSHELF__PORT_INT}
    volumes:
      - /config/audiobookshelf/config:/config
      - /config/audiobookshelf/metadata:/metadata
      - /libraries/media:/media
    environment:
      # ct envvars
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      # audiobookshelf envvars
    labels:
      # traefik labels
      - traefik.enable=true
      - traefik.http.routers.audiobookshelf.entrypoints=websecure
#     - traefik.http.routers.audiobookshelf.middlewares=authelia
      - traefik.http.routers.audiobookshelf.rule=Host(`shelf.${DOMAIN}`)
      - traefik.http.routers.audiobookshelf.tls.certresolver=cloudflare
      - traefik.http.services.audiobookshelf.loadbalancer.server.port=${AUDIOBOOKSHELF__PORT_INT}
      # flame labels
      - flame.type=app
      - flame.name=audiobookshelf
      - flame.url=https://shelf.${DOMAIN}/
      - flame.icon=book-open-page-variant

##### networking

networks:
  main:
    name: main
    external: true
