services:

# to-do:
# - crafty
#   - fix ports

################################################################################
##### crafty
################################################################################

  crafty:
    container_name: crafty
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    pull_policy: always
    restart: unless-stopped
    networks:
      - main
    ports:
      - ${CRAFTY__PORT_1_EXT}:${CRAFTY__PORT_1_INT}
      - ${CRAFTY__PORT_2_EXT}:${CRAFTY__PORT_2_INT}
      - ${CRAFTY__PORT_3_EXT}:${CRAFTY__PORT_3_INT}
      - ${CRAFTY__PORT_4_EXT}:${CRAFTY__PORT_4_INT}
      - ${CRAFTY__PORT_5_EXT}:${CRAFTY__PORT_5_INT}
    volumes:
      - /config/crafty/config:/crafty/app/config
      - /config/crafty/logs:/crafty/logs
      - /libraries/games/minecraft/backups:/crafty/backups
      - /libraries/games/minecraft/servers:/crafty/servers
      - /libraries/games/minecraft/import:/crafty/import
    environment:
      # ct envvars
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      # crafty envvars
    labels:
      # traefik labels
      - traefik.enable=true
      - traefik.http.routers.crafty.entrypoints=websecure
      - traefik.http.routers.crafty.middlewares=authelia
      - traefik.http.routers.crafty.rule=Host(`crafty.${DOMAIN}`)
      - traefik.http.routers.crafty.tls.certresolver=cloudflare
      - traefik.http.services.crafty.loadbalancer.server.port=${CRAFTY__PORT_2_INT}
      # flame labels
      - flame.type=app
      - flame.name=crafty
      - flame.url=https://crafty.${DOMAIN}/
      - flame.icon=minecraft

##### networking

networks:
  main:
    name: main
    external: true
