services:

# to-do: fix jellyfin ports
#        setup jellyfin oidc

################################################################################
##### jellyfin
################################################################################

  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    pull_policy: always
    restart: unless-stopped
    networks:
      - arr
    ports:
      - ${JELLYFIN__PORT_1_EXT}:${JELLYFIN__PORT_1_INT}
      - ${JELLYFIN__PORT_2_EXT}:${JELLYFIN__PORT_2_INT}
      - ${JELLYFIN__PORT_3_EXT}:${JELLYFIN__PORT_3_INT}/udp
      - ${JELLYFIN__PORT_4_EXT}:${JELLYFIN__PORT_4_INT}/udp
    volumes:
      - /config/jellyfin:/config
      - /libraries/media:/media
    environment:
      # ct envvars
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      # jellyfin envvars
      - JELLYFIN_PublishedServerUrl=https://jellyfin.${DOMAIN}
    labels:
      # traefik labels
      - traefik.enable=true
      - traefik.http.routers.jellyfin.entrypoints=websecure
#     - traefik.http.routers.jellyfin.middlewares=authelia   # let's not restrict for now
      - traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAIN}`)
      - traefik.http.routers.jellyfin.tls.certresolver=cloudflare
      - traefik.http.services.jellyfin.loadbalancer.server.port=${JELLYFIN__PORT_1_INT}
      # flame labels
      - flame.type=app
      - flame.name=jellyfin
      - flame.url=https://jellyfin.${DOMAIN}/
      - flame.icon=jellyfish

################################################################################
##### jellyseerr
################################################################################

  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    pull_policy: always
    restart: unless-stopped
    networks:
      - arr
#   ports:
#     - ${JELLYSEERR__PORT_EXT}:${JELLYSEERR__PORT_INT}
    volumes:
      - /config/jellyseerr:/app/config
    environment:
      # ct envvars
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      # jellyseerr envvars
      - LOG_LEVEL=debug
    labels:
      # traefik labels
      - traefik.enable=true
      - traefik.http.routers.jellyseerr.entrypoints=websecure
      - traefik.http.routers.jellyseerr.middlewares=authelia
      - traefik.http.routers.jellyseerr.rule=Host(`jellyseerr.${DOMAIN}`)
      - traefik.http.routers.jellyseerr.tls.certresolver=cloudflare
      - traefik.http.services.jellyseerr.loadbalancer.server.port=${JELLYSEERR__PORT_INT}
      # flame labels
      - flame.type=app
      - flame.name=jellyseerr
      - flame.url=https://jellyseerr.${DOMAIN}/
      - flame.icon=jellyfish-outline

##### networking

networks:
  arr:
    name: arr
    external: true
