services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    pull_policy: always
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Eastern
      - JELLYFIN_PublishedServerUrl=https://jellyfin.${DOMAIN}
    volumes:
      - /config/jellyfin:/config
      - /libraries:/libraries
    networks:
      arr:
        aliases:
          - jellyfin
    ports:
      - ${PORT_1_EXT}:${PORT_1_INT}
      - ${PORT_2_EXT}:${PORT_2_INT}
      - ${PORT_3_EXT}:${PORT_3_INT}/udp
      - ${PORT_4_EXT}:${PORT_4_INT}/udp
    labels:
      # traefik labels
      - traefik.enable=true
      - traefik.http.routers.jellyfin.entrypoints=web
      - traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAIN}`)
      - traefik.http.middlewares.jellyfin-redirect.redirectscheme.scheme=https
      - traefik.http.routers.jellyfin.middlewares=jellyfin-redirect
      - traefik.http.routers.jellyfin-secure.entrypoints=websecure
      - traefik.http.routers.jellyfin-secure.rule=Host(`jellyfin.${DOMAIN}`)
      - traefik.http.routers.jellyfin-secure.tls=true
      - traefik.http.services.jellyfin-service.loadbalancer.server.port=${PORT_1_INT}
      # flame labels
      - flame.type=app
      - flame.name=jellyfin
      - flame.url=https://jellyfin.${DOMAIN}/
      - flame.icon=jellyfish
networks:
  arr:
    name: arr
    external: true