services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    pull_policy: always
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Eastern
      - LOG_LEVEL=debug
    volumes:
      - /config/jellyseerr:/config
    networks:
      - arr
    ports:
      - ${PORT_1_EXT}:${PORT_1_INT}
    labels:
      # traefik labels
      - traefik.enable=true
      - traefik.http.routers.jellyseerr.entrypoints=web
      - traefik.http.routers.jellyseerr.rule=Host(`jellyseerr.${DOMAIN}`)
      - traefik.http.middlewares.jellyseerr-redirect.redirectscheme.scheme=https
      - traefik.http.routers.jellyseerr.middlewares=jellyseerr-redirect
      - traefik.http.routers.jellyseerr-secure.entrypoints=websecure
      - traefik.http.routers.jellyseerr-secure.rule=Host(`jellyseerr.${DOMAIN}`)
      - traefik.http.routers.jellyseerr-secure.tls=true
      - traefik.http.services.jellyseerr-service.loadbalancer.server.port=${PORT_1_INT}
      # flame labels
      - flame.type=app
      - flame.name=jellyseerr
      - flame.url=https://jellyseerr.${DOMAIN}/
      - flame.icon=jellyfish-outline
networks:
  arr:
    name: arr
    external: true