services:
  mariadb-nextcloud:
    container_name: mariadb-nextcloud
    image: mariadb:10.6
    pull_policy: always
    restart: unless-stopped
    volumes:
      - /config/mariadb-nextcloud:/var/lib/mysql
    networks:
      - main
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASS}
  nextcloud:
    container_name: nextcloud
    image: nextcloud:latest
    pull_policy: always
    restart: unless-stopped
    depends_on:
      - mariadb-nextcloud
    volumes:
      - /config/nextcloud:/var/www/html
    networks:
      - main
    ports:
      - ${PORT_1_EXT}:${PORT_1_INT}
    environment:
      - MYSQL_HOST=mariadb-nextcloud
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASS}
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.${DOMAIN},${MAIN_SUBNET}
    labels:
      # traefik labels
      - traefik.enable=true
      - traefik.http.routers.nextcloud.entrypoints=web
      - traefik.http.routers.nextcloud.rule=Host(`nextcloud.${DOMAIN}`)
      - traefik.http.middlewares.nextcloud-redirect.redirectscheme.scheme=https
      - traefik.http.routers.nextcloud.middlewares=nextcloud-redirect
      - traefik.http.routers.nextcloud-secure.entrypoints=websecure
      - traefik.http.routers.nextcloud-secure.rule=Host(`nextcloud.${DOMAIN}`)
      - traefik.http.routers.nextcloud-secure.tls=true
      - traefik.http.services.nextcloud-service.loadbalancer.server.port=${PORT_1_INT}
      # flame labels
      - flame.type=app
      - flame.name=nextcloud
      - flame.url=https://nextcloud.${DOMAIN}/
      - flame.icon=cloud
networks:
  main:
    name: main
    external: true