services:

################################################################################
##### silverbullet
################################################################################

  silverbullet:
    container_name: silverbullet
    image: zefhemel/silverbullet:latest
    pull_policy: always
    restart: unless-stopped
    networks:
      - main
#   ports:
#     - ${SILVERBULLET__PORT_EXT}:${SILVERBULLET__PORT_INT}
    volumes:
      - /libraries/notes:/space
    environment:
      # ct envvars
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      # silverbullet envvars
    labels:
      # traefik labels
      - traefik.enable=true
      - traefik.http.routers.silverbullet.entrypoints=websecure
      - traefik.http.routers.silverbullet.middlewares=authelia
      - traefik.http.routers.silverbullet.rule=Host(`bullet.${DOMAIN}`)
      - traefik.http.routers.silverbullet.tls.certresolver=cloudflare
      - traefik.http.services.silverbullet.loadbalancer.server.port=${SILVERBULLET__PORT_INT}
      # flame labels
      - flame.type=app
      - flame.name=silverbullet
      - flame.url=https://bullet.${DOMAIN}/
      - flame.icon=note

##### networking

networks:
  main:
    name: main
    external: true
