services:

################################################################################
##### suwayomi
################################################################################

  suwayomi:
    container_name: suwayomi
    image: ghcr.io/suwayomi/tachidesk:latest
    pull_policy: always
    restart: unless-stopped
    networks:
      - main
#   ports:
#     - ${SUWAYOMI__PORT_EXT}:${SUWAYOMI__PORT_INT}
    volumes:   # use keiyoushi extensions for sources
      - /config/suwayomi/downloads:/home/suwayomi/.local/share/Tachidesk/downloads   # order matters
      - /config/suwayomi:/home/suwayomi/.local/share/Tachidesk
    environment:
      # ct envvars
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      # suwayomi envvars
    labels:
      # traefik labels
      - traefik.enable=true
      - traefik.http.routers.suwayomi.entrypoints=websecure
      - traefik.http.routers.suwayomi.middlewares=authelia
      - traefik.http.routers.suwayomi.rule=Host(`suwayomi.${DOMAIN}`)
      - traefik.http.routers.suwayomi.tls.certresolver=cloudflare
      - traefik.http.services.suwayomi.loadbalancer.server.port=${SUWAYOMI__PORT_INT}
      # flame labels
      - flame.type=app
      - flame.name=suwayomi
      - flame.url=https://suwayomi.${DOMAIN}/
      - flame.icon=thought-bubble

##### networking

networks:
  main:
    name: main
    external: true
