services:

################################################################################
##### uptime-kuma
################################################################################

  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:latest
    pull_policy: always
    restart: unless-stopped
    networks:
      - main
#   ports:
#     - ${UPTIME_KUMA__PORT_EXT}:${UPTIME_KUMA__PORT_INT}
    volumes:
      - /config/uptime-kuma:/app/data
    environment:
      # ct envvars
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      # uptime-kuma envvars
    labels:
      # traefik labels
      - traefik.enable=true
      - traefik.http.routers.uptime-kuma.entrypoints=websecure
      - traefik.http.routers.uptime-kuma.middlewares=authelia
      - traefik.http.routers.uptime-kuma.rule=Host(`kuma.${DOMAIN}`)
      - traefik.http.routers.uptime-kuma.tls.certresolver=cloudflare
      - traefik.http.services.uptime-kuma.loadbalancer.server.port=${UPTIME_KUMA__PORT_INT}
      # flame labels
      - flame.type=app
      - flame.name=uptime kuma
      - flame.url=https://kuma.${DOMAIN}/
      - flame.icon=arrow-up-bold

##### networking

networks:
  main:
    name: main
    external: true
