services:
  vikunja:
    container_name: vikunja
    image: vikunja/vikunja:latest
    pull_policy: always
    restart: unless-stopped
    volumes:
      - /config/vikunja/db:/db
      - /config/vikunja/files:/app/vikunja/files
    networks:
      - main
    ports:
      - ${PORT_1_EXT}:${PORT_1_INT}
    environment:
      VIKUNJA_DATABASE_PATH: /db/vikunja.db
      #VIKUNJA_SERVICE_JWTSECRET: <a super secure random secret>
      VIKUNJA_SERVICE_PUBLICURL: https://vikunja.${DOMAIN}/
    labels:
      # traefik labels
      - traefik.enable=true
      - traefik.http.routers.vikunja.entrypoints=web
      - traefik.http.routers.vikunja.rule=Host(`vikunja.${DOMAIN}`)
      - traefik.http.middlewares.vikunja-redirect.redirectscheme.scheme=https
      - traefik.http.routers.vikunja.middlewares=vikunja-redirect
      - traefik.http.routers.vikunja-secure.entrypoints=websecure
      - traefik.http.routers.vikunja-secure.rule=Host(`vikunja.${DOMAIN}`)
      - traefik.http.routers.vikunja-secure.tls=true
      - traefik.http.services.vikunja-service.loadbalancer.server.port=${PORT_1_INT}
      # flame labels
      - flame.type=app
      - flame.name=vikunja
      - flame.url=https://vikunja.${DOMAIN}/
      - flame.icon=format-list-checks
networks:
  main:
    name: main
    external: true