services:

#####-------------------------------------------------------------------------------#--------------#
#####-- unbound --------------------------------------------------------------------#--------------#
#####-------------------------------------------------------------------------------#--------------#

  unbound:                                                                         ### <--
    image: mvance/unbound:latest                                                   ### <--
    container_name: ${SERVICE}
    pull_policy: always
    restart: unless-stopped
    environment:
      #-- docker -------------------------------------------------------------------#--------------#
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      #-- unbound ------------------------------------------------------------------#--------------#
      # - ...                                                                      ### <--

###-- networking -------------------------------------------------------------------#--------------#

    ports:
      - ${UNBOUND__PORT_EXT}:${UNBOUND__PORT_INT}
      - ${UNBOUND__PORT_EXT}:${UNBOUND__PORT_INT}/udp
    networks:
      - main
      - arr

networks:
  main:
    name: main
    external: true
  arr:
    name: arr
    external: true
