services:

#####-------------------------------------------------------------------------------#--------------#
#####-- watchtower -----------------------------------------------------------------#--------------#
#####-------------------------------------------------------------------------------#--------------#

  watchtower:                                                                      ### <--
    image: nickfedor/watchtower:latest                                             ### <--
    container_name: ${SERVICE}
    pull_policy: always
    restart: unless-stopped
    environment:
      #-- docker -------------------------------------------------------------------#--------------#
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      #-- watchtower ---------------------------------------------------------------#--------------#
      - WATCHTOWER_CLEANUP=true                                                    ### <--
      - WATCHTOWER_INCLUDE_STOPPED=true                                            ### <--
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock                                  ### <--

###-- networking -------------------------------------------------------------------#--------------#

    networks:
      - main
      - arr

networks:
  main:
    name: main
    external: true
  arr:
    name: arr
    external: true
