services:
  authelia:
    container_name: authelia
    image: authelia:latest
    pull_policy: always
    restart: unless-stopped
    volumes:
      - /config/authelia/config:/config
      - /config/authelia/secrets:/secrets
    networks:
      - main
    expose:
      - 9091
    environment:
      - AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE=/secrets/JWT_SECRET
      - AUTHELIA_SESSION_SECRET_FILE=/secrets/SESSION_SECRET
      - AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE=/secrets/STORAGE_PASSWORD
      - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/secrets/STORAGE_ENCRYPTION_KEY
      - TZ=US/Eastern
    labels:
      # traefik labels
      #- traefik.enable=true
      #- traefik.http.routers.authelia.entrypoints=web
      #- traefik.http.routers.authelia.rule=Host(`${HOST}`)
      #- traefik.http.middlewares.authelia-redirect.redirectscheme.scheme=https
      #- traefik.http.routers.authelia.middlewares=authelia-redirect
      #- traefik.http.routers.authelia-secure.entrypoints=websecure
      #- traefik.http.routers.authelia-secure.rule=Host(`${HOST}`)
      #- traefik.http.routers.authelia-secure.tls=true
      #- traefik.http.services.authelia-service.loadbalancer.server.port=${PORT_INT}
      # flame labels
      - flame.type=app
      - flame.name=authelia
      - flame.url=https://${HOST}/
      - flame.icon=account-box
networks:
  main:
    name: main
    external: true