services:
  authelia:
    container_name: authelia
    image: authelia:latest
    pull_policy: always
    restart: unless-stopped
    volumes:
      - /config/authelia/config:/config
      - /config/authelia/secrets:/secrets
    networks:
      - main
    expose:
      - 9091
    environment:
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: '/secrets/JWT_SECRET'
      AUTHELIA_SESSION_SECRET_FILE: '/secrets/SESSION_SECRET'
      AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE: '/secrets/STORAGE_PASSWORD'
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: '/secrets/STORAGE_ENCRYPTION_KEY'
networks:
  main:
    name: main
    external: true