services:

#####-------------------------------------------------------------------------------#--------------#
#####-- gluetun --------------------------------------------------------------------#--------------#
#####-------------------------------------------------------------------------------#--------------#

  gluetun:                                                                         ### <--
    image: qmcgaw/gluetun:latest                                                   ### <--
    container_name: ${SERVICE}
    pull_policy: always
    restart: unless-stopped
    environment:
      #-- docker -------------------------------------------------------------------#--------------#
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      #-- gluetun ------------------------------------------------------------------#--------------#
      - SERVER_CITIES=${GLUETUN__SERVER_CITIES}                                    ### <--
      - VPN_SERVICE_PROVIDER=${GLUETUN__VPN_SERVICE_PROVIDER}                      ### <--
      - VPN_TYPE=${GLUETUN__VPN_TYPE}                                              ### <--
      - WIREGUARD_ADDRESSES=${GLUETUN__WIREGUARD_ADDRESSES}                        ### <--
      - WIREGUARD_PRIVATE_KEY=${GLUETUN__WIREGUARD_PRIVATE_KEY}                    ### <--
      - UPDATER_PERIOD=6h                                                          ### <--
    volumes:
      - /config/gluetun:/gluetun                                                   ### <--
    cap_add:
      - NET_ADMIN                                                                  ### <--
    devices:
      - /dev/net/tun:/dev/net/tun                                                  ### <--

###-- networking -------------------------------------------------------------------#--------------#

    ports:
      - ${PROWLARR__PORT_EXT}:${PROWLARR__PORT_INT}
      - ${QBITTORRENT__PORT_1_EXT}:${QBITTORRENT__PORT_1_INT}
      - ${QBITTORRENT__PORT_2_EXT}:${QBITTORRENT__PORT_2_INT}
      - ${QBITTORRENT__PORT_2_EXT}:${QBITTORRENT__PORT_2_INT}/udp
      - ${SABNZBD__PORT_EXT}:${SABNZBD__PORT_INT}
    networks:
#     - main
      - arr

networks:
# main:
#   name: main
#   external: true
  arr:
    name: arr
    external: true
