services:

#####-------------------------------------------------------------------------------#--------------#
#####-- jellyfin -------------------------------------------------------------------#--------------#
#####-------------------------------------------------------------------------------#--------------#

  jellyfin:                                                                        ### <--
    image: lscr.io/linuxserver/jellyfin:latest                                     ### <--
    container_name: ${SERVICE}
    pull_policy: always
    restart: unless-stopped
    labels:
      #-- traefik ------------------------------------------------------------------#--------------#
      - traefik.enable=true
      - traefik.http.routers.${SERVICE}.entrypoints=websecure
#     - traefik.http.routers.${SERVICE}.middlewares=authelia                        # oidc
      - traefik.http.routers.${SERVICE}.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.${SERVICE}.tls.certresolver=cloudflare
      - traefik.http.services.${SERVICE}.loadbalancer.server.port=${SERVICE_PORT}
    environment:
      #-- docker -------------------------------------------------------------------#--------------#
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      #-- jellyfin -----------------------------------------------------------------#--------------#
      - JELLYFIN_PublishedServerUrl=https://{SUBDOMAIN}.${DOMAIN}                  ### <--
    volumes:
      - /config/jellyfin:/config                                                   ### <--
      - /libraries/media:/media                                                    ### <--

###-- networking -------------------------------------------------------------------#--------------#

    ports:
      - ${JELLYFIN__PORT_1_EXT}:${JELLYFIN__PORT_1_INT}                             # debug
      - ${JELLYFIN__PORT_2_EXT}:${JELLYFIN__PORT_2_INT}                             # debug
      - ${JELLYFIN__PORT_3_EXT}:${JELLYFIN__PORT_3_INT}/udp                         # debug
      - ${JELLYFIN__PORT_4_EXT}:${JELLYFIN__PORT_4_INT}/udp                         # debug
    networks:
#     - main
      - arr

networks:
# main:
#   name: main
#   external: true
  arr:
    name: arr
    external: true
