services:

#####-------------------------------------------------------------------------------#--------------#
#####-- unpackerr ------------------------------------------------------------------#--------------#
#####-------------------------------------------------------------------------------#--------------#

  unpackerr:                                                                       ### <--
    image: ghcr.io/hotio/unpackerr:latest                                          ### <--
    container_name: ${SERVICE}
    pull_policy: always
    restart: unless-stopped
    environment:
      #-- docker -------------------------------------------------------------------#--------------#
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      #-- unpackerr ----------------------------------------------------------------#--------------#
      # - ...                                                                      ### <--
    volumes:
      - /config/unpackerr:/config                                                  ### <--
      - /libraries/downloads:/downloads                                            ### <--

###-- networking -------------------------------------------------------------------#--------------#

    networks:
      - main
      - arr

networks:
  main:
    name: main
    external: true
  arr:
    name: arr
    external: true
