services:

#####-------------------------------------------------------------------------------#--------------#
#####-- memos ----------------------------------------------------------------------#--------------#
#####-------------------------------------------------------------------------------#--------------#

  memos:                                                                           ### <--
    image: neosmemo/memos:stable                                                   ### <--
    container_name: ${SERVICE}
    pull_policy: always
    restart: unless-stopped
    labels:
      #-- traefik ------------------------------------------------------------------#--------------#
      - traefik.enable=true
      - traefik.http.routers.${SERVICE}.entrypoints=websecure
#     - traefik.http.routers.${SERVICE}.middlewares=authelia                        # oidc
      - traefik.http.routers.${SERVICE}.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.${SERVICE}.tls.certresolver=cloudflare
      - traefik.http.services.${SERVICE}.loadbalancer.server.port=${SERVICE_PORT}
    environment:
      #-- docker -------------------------------------------------------------------#--------------#
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      #-- memos --------------------------------------------------------------------#--------------#
      - MEMOS_INSTANCE_URL=https://${SERVICE}.${DOMAIN}                            ### <--
    volumes:
      - /config/memos/:/var/opt/memos                                              ### <--

###-- networking -------------------------------------------------------------------#--------------#

    ports:
      - ${MEMOS__PORT_EXT}:${MEMOS__PORT_INT}
    networks:
      - main
#     - arr

networks:
  main:
    name: main
    external: true
# arr:
#   name: arr
#   external: true
