services:

#####-------------------------------------------------------------------------------#--------------#
#####-- lidarr ---------------------------------------------------------------------#--------------#
#####-------------------------------------------------------------------------------#--------------#

  lidarr:                                                                          ### <--
    image: lscr.io/linuxserver/lidarr:latest                                       ### <--
    container_name: ${SERVICE}
    pull_policy: always
    restart: unless-stopped
    labels:
      #-- traefik ------------------------------------------------------------------#--------------#
      - traefik.enable=true
      - traefik.http.routers.${SERVICE}.entrypoints=websecure
      - traefik.http.routers.${SERVICE}.middlewares=authelia
      - traefik.http.routers.${SERVICE}.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.${SERVICE}.tls.certresolver=cloudflare
      - traefik.http.services.${SERVICE}.loadbalancer.server.port=${SERVICE_PORT}
    environment:
      #-- docker -------------------------------------------------------------------#--------------#
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      #-- lidarr -------------------------------------------------------------------#--------------#
      # - ...                                                                      ### <--
    volumes:
      - /config/lidarr:/config                                                     ### <--
      - /libraries/media/music:/music                                              ### <--
      - /libraries/downloads/torrents/complete/lidarr:/torrents/complete/lidarr    ### <--
      - /libraries/downloads/usenet/complete/lidarr:/usenet/complete/lidarr        ### <--

###-- networking -------------------------------------------------------------------#--------------#

    ports:
      - ${LIDARR__PORT_EXT}:${LIDARR__PORT_INT}
    networks:
#     - main
      - arr

networks:
# main:
#   name: main
#   external: true
  arr:
    name: arr
    external: true
