services:

#####-------------------------------------------------------------------------------#--------------#
#####-- paperless-redis ------------------------------------------------------------#--------------#
#####-------------------------------------------------------------------------------#--------------#

  paperless-redis:                                                                 ### <--
    image: docker.io/library/redis:8                                               ### <--
    container_name: ${SERVICE_1}
    pull_policy: always
    restart: unless-stopped
    volumes:
      - /config/${SERVICE_1}:/data                                                 ### <--


###-- networking -------------------------------------------------------------------#--------------#

    networks:
      - main
#     - arr



#####-------------------------------------------------------------------------------#--------------#
#####-- paperless-postgres ---------------------------------------------------------#--------------#
#####-------------------------------------------------------------------------------#--------------#

  paperless-postgres:                                                              ### <--
    image: docker.io/library/postgres:18                                           ### <--
    container_name: ${SERVICE_2}
    pull_policy: always
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${PAPERLESS_POSTGRES__DB}                                      ### <--
      - POSTGRES_USER=${PAPERLESS_POSTGRES__USER}                                  ### <--
      - POSTGRES_PASSWORD=${PAPERLESS_POSTGRES__PASSWORD}                          ### <--
    volumes:
      - /config/${SERVICE_2}:/var/lib/postgresql                                   ### <--

###-- networking -------------------------------------------------------------------#--------------#

    networks:
      - main
#     - arr



#####-------------------------------------------------------------------------------#--------------#
#####-- paperless ------------------------------------------------------------------#--------------#
#####-------------------------------------------------------------------------------#--------------#

  paperless:
    depends_on:                                                                    ### <--
      - ${SERVICE_1}                                                               ### <--
      - ${SERVICE_2}                                                               ### <--
    image: ghcr.io/paperless-ngx/paperless-ngx:latest                              ### <--
    container_name: ${SERVICE_3}
    pull_policy: always
    restart: unless-stopped
    labels:
      #-- traefik ------------------------------------------------------------------#--------------#
      - traefik.enable=true
      - traefik.http.routers.${SERVICE_3}.entrypoints=websecure
      - traefik.http.routers.${SERVICE_3}.middlewares=authelia
      - traefik.http.routers.${SERVICE_3}.rule=Host(`${SUBDOMAIN_3}.${DOMAIN}`)
      - traefik.http.routers.${SERVICE_3}.tls.certresolver=cloudflare
      - traefik.http.services.${SERVICE_3}.loadbalancer.server.port=${SERVICE_PORT_3}
    environment:
      #-- docker -------------------------------------------------------------------#--------------#
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      #-- paperless ----------------------------------------------------------------#--------------#
      - PAPERLESS_URL=https://${SUBDOMAIN_3}.${DOMAIN}                             ### <--
      - PAPERLESS_AUTO_LOGIN_USERNAME=${PAPERLESS__AUTO_LOGIN_USERNAME}            ### <--
      - PAPERLESS_ADMIN_USER=${PAPERLESS__ADMIN_USER}                              ### <--
      - PAPERLESS_ADMIN_PASSWORD=${PAPERLESS__ADMIN_PASSWORD}                      ### <--
      - PAPERLESS_OCR_LANGUAGE=eng                                                 ### <--
      - PAPERLESS_REDIS=redis://${SERVICE_1}:6379                                  ### <--
      - PAPERLESS_DBHOST=${SERVICE_2}                                              ### <--
      - PAPERLESS_DBNAME=${PAPERLESS_POSTGRES__DB}                                 ### <--
      - PAPERLESS_DBUSER=${PAPERLESS_POSTGRES__USER}                               ### <--
      - PAPERLESS_DBPASS=${PAPERLESS_POSTGRES__PASSWORD}                           ### <--
    volumes:
      - /config/${SERVICE_3}:/usr/src/paperless/data                               ### <--
      - /libraries/documents:/usr/src/paperless/media                              ### <--
      - ./export:/usr/src/paperless/export                                         ### <--
      - ./consume:/usr/src/paperless/consume                                       ### <--

###-- networking -------------------------------------------------------------------#--------------#

    ports:
      - ${PAPERLESS__PORT_EXT}:${PAPERLESS__PORT_INT}
    networks:
      - main
#     - arr



networks:
  main:
    name: main
    external: true
# arr:
#   name: arr
#   external: true
