services:

#####-------------------------------------------------------------------------------#--------------#
#####-- profilarr ------------------------------------------------------------------#--------------#
#####-------------------------------------------------------------------------------#--------------#

  profilarr:                                                                       ### <--
    image: santiagosayshey/profilarr:latest                                        ### <--
    container_name: ${SERVICE}
    pull_policy: always
    restart: unless-stopped
    labels:
      #-- traefik ------------------------------------------------------------------#--------------#
      - traefik.enable=true
      - traefik.http.routers.${SERVICE}.entrypoints=websecure
      - traefik.http.routers.${SERVICE}.middlewares=authelia
      - traefik.http.routers.${SERVICE}.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.${SERVICE}.tls.certresolver=cloudflare
      - traefik.http.services.${SERVICE}.loadbalancer.server.port=${SERVICE_PORT}
    environment:
      #-- docker -------------------------------------------------------------------#--------------#
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      #-- profilarr ----------------------------------------------------------------#--------------#
      # - ...                                                                      ### <--
    volumes:
      - /config/profilarr:/config                                                  ### <--

###-- networking -------------------------------------------------------------------#--------------#

#   ports:
#     - ${PROFILARR__PORT_EXT}:${PROFILARR__PORT_INT}                               # debug
    networks:
#     - main
      - arr

networks:
# main:
#   name: main
#   external: true
  arr:
    name: arr
    external: true
