services:

#####-------------------------------------------------------------------------------#--------------#
#####-- authelia -------------------------------------------------------------------#--------------#
#####-------------------------------------------------------------------------------#--------------#

  authelia:                                                                        ### <--
    image: authelia/authelia:latest                                                ### <--
    container_name: ${SERVICE}
    pull_policy: always
    restart: unless-stopped
    labels:
      #-- traefik ------------------------------------------------------------------#--------------#
      - traefik.enable=true
      - traefik.http.routers.${SERVICE}.entrypoints=websecure
#     - traefik.http.routers.${SERVICE}.middlewares=authelia                        # public
      - traefik.http.routers.${SERVICE}.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.${SERVICE}.tls.certresolver=cloudflare
      - traefik.http.services.${SERVICE}.loadbalancer.server.port=${SERVICE_PORT}
    environment:
      #-- docker -------------------------------------------------------------------#--------------#
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      #-- authelia -----------------------------------------------------------------#--------------#
      - AUTHELIA_JWT_SECRET=${AUTHELIA__JWT_SECRET}                                ### <--
      - AUTHELIA_SESSION_SECRET=${AUTHELIA__SESSION_SECRET}                        ### <--
      - AUTHELIA_STORAGE_ENCRYPTION_KEY=${AUTHELIA__STORAGE_ENCRYPTION_KEY}        ### <--
    volumes:
      - /config/authelia:/config                                                   ### <--

###-- networking -------------------------------------------------------------------#--------------#

    ports:
      - ${AUTHELIA__PORT_EXT}:${AUTHELIA__PORT_INT}
    networks:
      - main
      - arr

networks:
  main:
    name: main
    external: true
  arr:
    name: arr
    external: true
