services:

#####-------------------------------------------------------------------------------#--------------#
#####-- pihole ---------------------------------------------------------------------#--------------#
#####-------------------------------------------------------------------------------#--------------#

  pihole:                                                                          ### <--
    image: pihole/pihole:latest                                                    ### <--
    container_name: ${SERVICE}
    pull_policy: always
    restart: unless-stopped
    labels:
      #-- traefik ------------------------------------------------------------------#--------------#
      - traefik.enable=true
      - traefik.http.routers.${SERVICE}.entrypoints=websecure
#     - traefik.http.routers.${SERVICE}.middlewares=authelia                        # public
      - traefik.http.routers.${SERVICE}.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.${SERVICE}.tls.certresolver=cloudflare
      - traefik.http.services.${SERVICE}.loadbalancer.server.port=${SERVICE_PORT}
    environment:
      #-- docker -------------------------------------------------------------------#--------------#
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      #-- pihole -------------------------------------------------------------------#--------------#
      - DNSSEC=true                                                                ### <--
      - PIHOLE_DNS_=${IP}#${UNBOUND__PORT_INT}                                     ### <--
      - TEMPERATUREUNIT=f                                                          ### <--
      - WEBPASSWORD=${PIHOLE__WEBPASSWORD}                                         ### <--
      - WEBTHEME=default-darker                                                    ### <--
    volumes:
      - /config/pihole:/etc/pihole                                                 ### <--
      - /config/pihole/dnsmasq.d:/etc/dnsmasq.d                                    ### <--

###-- networking -------------------------------------------------------------------#--------------#

    ports:
      - ${IP}:${PIHOLE__PORT_1_EXT}:${PIHOLE__PORT_1_INT}
      - ${IP}:${PIHOLE__PORT_1_EXT}:${PIHOLE__PORT_1_INT}/udp
      - ${PIHOLE__PORT_2_EXT}:${PIHOLE__PORT_2_INT}
    networks:
      - main
      - arr

networks:
  main:
    name: main
    external: true
  arr:
    name: arr
    external: true
