services:

#####-------------------------------------------------------------------------------#--------------#
#####-- qbittorrent ----------------------------------------------------------------#--------------#
#####-------------------------------------------------------------------------------#--------------#

  qbittorrent:                                                                     ### <--
    image: lscr.io/linuxserver/qbittorrent:latest                                  ### <--
    container_name: ${SERVICE}
    pull_policy: always
    restart: unless-stopped
    labels:
      #-- traefik ------------------------------------------------------------------#--------------#
      - traefik.enable=true
      - traefik.http.routers.${SERVICE}.entrypoints=websecure
      - traefik.http.routers.${SERVICE}.middlewares=authelia
      - traefik.http.routers.${SERVICE}.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.${SERVICE}.tls.certresolver=cloudflare
      - traefik.http.services.${SERVICE}.loadbalancer.server.port=${SERVICE_PORT}
    environment:
      #-- docker -------------------------------------------------------------------#--------------#
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      #-- qbittorrent --------------------------------------------------------------#--------------#
      - WEBUI_PORT=${QBITTORRENT__PORT_1_INT}                                      ### <--
    volumes:
      - /config/qbittorrent:/config                                                ### <--
      - /libraries/downloads/torrents:/torrents                                    ### <--

###-- networking -------------------------------------------------------------------#--------------#

    network_mode: container:gluetun
