services:

# to-do:
# - traefik
#   - fix commands
#   - fix labels

################################################################################
##### traefik
################################################################################

  traefik:
    container_name: traefik
    image: traefik:latest
    pull_policy: always
    restart: unless-stopped
    networks:
      - main
      - arr
    ports:
      - ${TRAEFIK__PORT_1_EXT}:${TRAEFIK__PORT_1_INT}
      - ${TRAEFIK__PORT_2_EXT}:${TRAEFIK__PORT_2_INT}
      - ${TRAEFIK__PORT_3_EXT}:${TRAEFIK__PORT_3_INT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /config/traefik:/letsencrypt
    environment:
      # ct envvars
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      # traefik envvars
      - CF_API_EMAIL=${TRAEFIK__CF_API_EMAIL}
      - CF_API_KEY=${TRAEFIK__CF_API_KEY}
    command:
      - --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --serverstransport.insecureskipverify=true
      - --entrypoints.web.address=:${TRAEFIK__PORT_1_INT}
      - --entrypoints.websecure.address=:${TRAEFIK__PORT_2_INT}
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      # - --certificatesresolvers.cloudflare.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.cloudflare.acme.email=${TRAEFIK__CF_API_EMAIL}
      - --certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json
    labels:
      # traefik labels
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=web
      - traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)
      - traefik.http.middlewares.traefik-redirect.redirectscheme.scheme=https
      - traefik.http.routers.traefik.middlewares=traefik-redirect
      - traefik.http.routers.traefik-secure.entrypoints=websecure
      - traefik.http.routers.traefik-secure.rule=Host(`traefik.${DOMAIN}`)
      - traefik.http.routers.traefik-secure.tls=true
      - traefik.http.routers.traefik-secure.tls.certresolver=cloudflare
      - traefik.http.routers.traefik-secure.tls.domains[0].main=${DOMAIN}
      - traefik.http.routers.traefik-secure.tls.domains[0].sans=*.${DOMAIN}
      - traefik.http.routers.traefik-secure.tls.domains[1].main=${DOMAIN_ALT}
      - traefik.http.routers.traefik-secure.tls.domains[1].sans=*.${DOMAIN_ALT}
      # - traefik.http.routers.traefik-secure.service=api@internal
      - traefik.http.services.traefik-service.loadbalancer.server.port=${TRAEFIK__PORT_3_INT}
      - traefik.http.middlewares.authelia.forwardauth.address=http://authelia:${AUTHELIA__PORT_INT}/api/verify?rd=https://auth.${DOMAIN}
      - traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true
      - traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email
      # flame labels
      - flame.type=app
      - flame.name=traefik
      - flame.url=https://traefik.${DOMAIN}/
      - flame.icon=traffic-light

##### networking

networks:
  main:
    name: main
    external: true
  arr:
    name: arr
    external: true
