services:

#####-------------------------------------------------------------------------------#--------------#
#####-- tdarr ----------------------------------------------------------------------#--------------#
#####-------------------------------------------------------------------------------#--------------#

  tdarr:                                                                           ### <--
    image: ghcr.io/haveagitgat/tdarr:latest                                        ### <--
    container_name: ${SERVICE}
    pull_policy: always
    restart: unless-stopped

    network_mode: bridge
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
    environment:
      #-- docker -------------------------------------------------------------------#--------------#
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      #-- tdarr --------------------------------------------------------------------#--------------#
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=7
      - nodeName=MyInternalNode
      - auth=false
      - openBrowser=true
      - maxLogSizeMB=10
      - cronPluginUpdate=
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /config/tdarr/server:/app/server
      - /config/tdarr/configs:/app/configs
      - /config/tdarr/logs:/app/logs
      - /libraries:/media
      - /transcode_cache:/temp

    devices:
      - /dev/dri:/dev/dri
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    
#####-------------------------------------------------------------------------------#--------------#
#####-- tdarr-node -----------------------------------------------------------------#--------------#
#####-------------------------------------------------------------------------------#--------------#

  tdarr-node:
    image: ghcr.io/haveagitgat/tdarr_node:latest
    container_name: ${SERVICE}
    pull_policy: always
    restart: unless-stopped

    network_mode: service:tdarr
    environment:
      #-- docker -------------------------------------------------------------------#--------------#
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      #-- tdarr-node ---------------------------------------------------------------#--------------#
      - UMASK_SET=002
      - nodeName=MyExternalNode
      - serverIP=0.0.0.0
      - serverPort=8266
      - inContainer=true
      - ffmpegVersion=7
      - nodeType=mapped
      - priority=-1
      - cronPluginUpdate=
      - apiKey=
      - maxLogSizeMB=10
      - pollInterval=2000
      - startPaused=false
      - transcodegpuWorkers=1
      - transcodecpuWorkers=2
      - healthcheckgpuWorkers=1
      - healthcheckcpuWorkers=1
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all

    volumes:
      - /config/tdarr/configs:/app/configs
      - /config/tdarr/logs:/app/logs
      - /libraries:/media
      - /transcode_cache:/temp

    devices:
      - /dev/dri:/dev/dri
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
