services:

################################################################################
##### bazarr
################################################################################

  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    pull_policy: always
    restart: unless-stopped
    network_mode: container:gluetun
    volumes:
      - /config/bazarr:/config
      - /libraries:/libraries
    environment:
      # ct envvars
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      # bazarr envvars
    labels:
      # traefik labels
      - traefik.enable=true
      - traefik.http.routers.bazarr.entrypoints=websecure
      - traefik.http.routers.bazarr.middlewares=authelia
      - traefik.http.routers.bazarr.rule=Host(`bazarr.${DOMAIN}`)
      - traefik.http.routers.bazarr.tls.certresolver=cloudflare
      - traefik.http.services.bazarr.loadbalancer.server.port=${BAZARR__PORT_INT}
      # flame labels
      - flame.type=app
      - flame.name=bazarr
      - flame.url=https://bazarr.${DOMAIN}/
      - flame.icon=subtitles

################################################################################
##### lidarr
################################################################################

  lidarr:
    container_name: lidarr
    image: lscr.io/linuxserver/lidarr:latest
    pull_policy: always
    restart: unless-stopped
    network_mode: container:gluetun
    volumes:
      - /config/lidarr:/config
      - /libraries/media/music:/music
      - /libraries/downloads/torrents/complete/lidarr:/torrents/complete/lidarr
      - /libraries/downloads/usenet/complete/lidarr:/usenet/complete/lidarr
    environment:
      # ct envvars
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      # lidarr envvars
    labels:
      # traefik labels
      - traefik.enable=true
      - traefik.http.routers.lidarr.entrypoints=websecure
      - traefik.http.routers.lidarr.middlewares=authelia
      - traefik.http.routers.lidarr.rule=Host(`lidarr.${DOMAIN}`)
      - traefik.http.routers.lidarr.tls.certresolver=cloudflare
      - traefik.http.services.lidarr.loadbalancer.server.port=${LIDARR__PORT_INT}
      # flame labels
      - flame.type=app
      - flame.name=lidarr
      - flame.url=https://lidarr.${DOMAIN}/
      - flame.icon=music

################################################################################
##### prowlarr
################################################################################

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    pull_policy: always
    restart: unless-stopped
    network_mode: container:gluetun
    volumes:
      - /config/prowlarr:/config
    environment:
      # ct envvars
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      # prowlarr envvars
    labels:
      # traefik labels
      - traefik.enable=true
      - traefik.http.routers.prowlarr.entrypoints=websecure
      - traefik.http.routers.prowlarr.middlewares=authelia
      - traefik.http.routers.prowlarr.rule=Host(`prowlarr.${DOMAIN}`)
      - traefik.http.routers.prowlarr.tls.certresolver=cloudflare
      - traefik.http.services.prowlarr.loadbalancer.server.port=${PROWLARR__PORT_INT}
      # flame labels
      - flame.type=app
      - flame.name=prowlarr
      - flame.url=https://prowlarr.${DOMAIN}/
      - flame.icon=file-find

################################################################################
##### radarr-1080
################################################################################

  radarr-1080:
    container_name: radarr-1080
    image: lscr.io/linuxserver/radarr:latest
    pull_policy: always
    restart: unless-stopped
    network_mode: container:gluetun
    volumes:
      - /config/radarr-1080:/config
      - /libraries/media/movies/1080:/movies/1080
      - /libraries/downloads/torrents/complete/radarr-1080:/torrents/complete/radarr-1080
      - /libraries/downloads/usenet/complete/radarr-1080:/usenet/complete/radarr-1080
    environment:
      # ct envvars
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      # radarr-1080 envvars
    labels:
      # traefik labels
      - traefik.enable=true
      - traefik.http.routers.radarr-1080.entrypoints=websecure
      - traefik.http.routers.radarr-1080.middlewares=authelia
      - traefik.http.routers.radarr-1080.rule=Host(`radarr-1080.${DOMAIN}`)
      - traefik.http.routers.radarr-1080.tls.certresolver=cloudflare
      - traefik.http.services.radarr-1080.loadbalancer.server.port=${RADARR_1080__PORT_INT}
      # flame labels
      - flame.type=app
      - flame.name=radarr-1080
      - flame.url=https://radarr-1080.${DOMAIN}/
      - flame.icon=movie

################################################################################
##### radarr-2160
################################################################################

  radarr-2160:
    container_name: radarr-2160
    image: lscr.io/linuxserver/radarr:latest
    pull_policy: always
    restart: unless-stopped
    network_mode: container:gluetun
    volumes:
      - /config/radarr-2160:/config
      - /libraries/media/movies/2160:/movies/2160
      - /libraries/downloads/torrents/complete/radarr-2160:/torrents/complete/radarr-2160
      - /libraries/downloads/usenet/complete/radarr-2160:/usenet/complete/radarr-2160
    environment:
      # ct envvars
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      # radarr-2160 envvars
    labels:
      # traefik labels
      - traefik.enable=true
      - traefik.http.routers.radarr-2160.entrypoints=websecure
      - traefik.http.routers.radarr-2160.middlewares=authelia
      - traefik.http.routers.radarr-2160.rule=Host(`radarr-2160.${DOMAIN}`)
      - traefik.http.routers.radarr-2160.tls.certresolver=cloudflare
      - traefik.http.services.radarr-2160.loadbalancer.server.port=${RADARR_2160__PORT_INT}
      # flame labels
      - flame.type=app
      - flame.name=radarr-2160
      - flame.url=https://radarr-2160.${DOMAIN}/
      - flame.icon=movie

################################################################################
##### radarr-anime
################################################################################

  radarr-anime:
    container_name: radarr-anime
    image: lscr.io/linuxserver/radarr:latest
    pull_policy: always
    restart: unless-stopped
    network_mode: container:gluetun
    volumes:
      - /config/radarr-anime:/config
      - /libraries/media/movies/anime:/movies/anime
      - /libraries/downloads/torrents/complete/radarr-anime:/torrents/complete/radarr-anime
      - /libraries/downloads/usenet/complete/radarr-anime:/usenet/complete/radarr-anime
    environment:
      # ct envvars
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      # radarr-anime envvars
    labels:
      # traefik labels
      - traefik.enable=true
      - traefik.http.routers.radarr-anime.entrypoints=websecure
      - traefik.http.routers.radarr-anime.middlewares=authelia
      - traefik.http.routers.radarr-anime.rule=Host(`radarr-anime.${DOMAIN}`)
      - traefik.http.routers.radarr-anime.tls.certresolver=cloudflare
      - traefik.http.services.radarr-anime.loadbalancer.server.port=${RADARR_ANIME__PORT_INT}
      # flame labels
      - flame.type=app
      - flame.name=radarr-anime
      - flame.url=https://radarr-anime.${DOMAIN}/
      - flame.icon=movie

################################################################################
##### readarr
################################################################################

  readarr:
    container_name: readarr
    image: lscr.io/linuxserver/readarr:develop
    pull_policy: always
    restart: unless-stopped
    network_mode: container:gluetun
    volumes:
      - /config/readarr:/config
      - /libraries/media/books:/books
      - /libraries/downloads/torrents/complete/readarr:/torrents/complete/readarr
      - /libraries/downloads/usenet/complete/readarr:/usenet/complete/readarr
    environment:
      # ct envvars
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      # readarr envvars
    labels:
      # traefik labels
      - traefik.enable=true
      - traefik.http.routers.readarr.entrypoints=websecure
      - traefik.http.routers.readarr.middlewares=authelia
      - traefik.http.routers.readarr.rule=Host(`readarr.${DOMAIN}`)
      - traefik.http.routers.readarr.tls.certresolver=cloudflare
      - traefik.http.services.readarr.loadbalancer.server.port=${READARR__PORT_INT}
      # flame labels
      - flame.type=app
      - flame.name=readarr
      - flame.url=https://readarr.${DOMAIN}/
      - flame.icon=book-open-page-variant

################################################################################
##### sonarr-1080
################################################################################

  sonarr-1080:
    container_name: sonarr-1080
    image: lscr.io/linuxserver/sonarr:latest
    pull_policy: always
    restart: unless-stopped
    network_mode: container:gluetun
    volumes:
      - /config/sonarr-1080:/config
      - /libraries/media/shows/1080:/shows/1080
      - /libraries/downloads/torrents/complete/sonarr-1080:/torrents/complete/sonarr-1080
      - /libraries/downloads/usenet/complete/sonarr-1080:/usenet/complete/sonarr-1080
    environment:
      # ct envvars
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      # sonarr-1080 envvars
    labels:
      # traefik labels
      - traefik.enable=true
      - traefik.http.routers.sonarr-1080.entrypoints=websecure
      - traefik.http.routers.sonarr-1080.middlewares=authelia
      - traefik.http.routers.sonarr-1080.rule=Host(`sonarr-1080.${DOMAIN}`)
      - traefik.http.routers.sonarr-1080.tls.certresolver=cloudflare
      - traefik.http.services.sonarr-1080.loadbalancer.server.port=${SONARR_1080__PORT_INT}
      # flame labels
      - flame.type=app
      - flame.name=sonarr-1080
      - flame.url=https://sonarr-1080.${DOMAIN}/
      - flame.icon=television-classic

################################################################################
##### sonarr-2160
################################################################################

  sonarr-2160:
    container_name: sonarr-2160
    image: lscr.io/linuxserver/sonarr:latest
    pull_policy: always
    restart: unless-stopped
    network_mode: container:gluetun
    volumes:
      - /config/sonarr-2160:/config
      - /libraries/media/shows/2160:/shows/2160
      - /libraries/downloads/torrents/complete/sonarr-2160:/torrents/complete/sonarr-2160
      - /libraries/downloads/usenet/complete/sonarr-2160:/usenet/complete/sonarr-2160
    environment:
      # ct envvars
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      # sonarr-2160 envvars
    labels:
      # traefik labels
      - traefik.enable=true
      - traefik.http.routers.sonarr-2160.entrypoints=websecure
      - traefik.http.routers.sonarr-2160.middlewares=authelia
      - traefik.http.routers.sonarr-2160.rule=Host(`sonarr-2160.${DOMAIN}`)
      - traefik.http.routers.sonarr-2160.tls.certresolver=cloudflare
      - traefik.http.services.sonarr-2160.loadbalancer.server.port=${SONARR_2160__PORT_INT}
      # flame labels
      - flame.type=app
      - flame.name=sonarr-2160
      - flame.url=https://sonarr-2160.${DOMAIN}/
      - flame.icon=television-classic

################################################################################
##### sonarr-anime
################################################################################

  sonarr-anime:
    container_name: sonarr-anime
    image: lscr.io/linuxserver/sonarr:latest
    pull_policy: always
    restart: unless-stopped
    network_mode: container:gluetun
    volumes:
      - /config/sonarr-anime:/config
      - /libraries/media/shows/anime:/shows/anime
      - /libraries/downloads/torrents/complete/sonarr-anime:/torrents/complete/sonarr-anime
      - /libraries/downloads/usenet/complete/sonarr-anime:/usenet/complete/sonarr-anime
    environment:
      # ct envvars
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      # sonarr-anime envvars
    labels:
      # traefik labels
      - traefik.enable=true
      - traefik.http.routers.sonarr-anime.entrypoints=websecure
      - traefik.http.routers.sonarr-anime.middlewares=authelia
      - traefik.http.routers.sonarr-anime.rule=Host(`sonarr-anime.${DOMAIN}`)
      - traefik.http.routers.sonarr-anime.tls.certresolver=cloudflare
      - traefik.http.services.sonarr-anime.loadbalancer.server.port=${SONARR_ANIME__PORT_INT}
      # flame labels
      - flame.type=app
      - flame.name=sonarr-anime
      - flame.url=https://sonarr-anime.${DOMAIN}/
      - flame.icon=television-classic
