services:
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    restart: unless-stopped
    network_mode: container:gluetun
    volumes:
      - /config/qbittorrent:/config
      - /libraries/downloads/torrents:/torrents
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=${TZ}
      - WEBUI_PORT=${QBITTORRENT_PORT_INT}
    labels:
      # traefik labels
      - traefik.enable=true
      - traefik.http.routers.qbittorrent.entrypoints=web
      - traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.${DOMAIN}`)
      - traefik.http.middlewares.qbittorrent-redirect.redirectscheme.scheme=https
      - traefik.http.routers.qbittorrent.middlewares=qbittorrent-redirect
      - traefik.http.routers.qbittorrent-secure.entrypoints=websecure
      - traefik.http.routers.qbittorrent-secure.rule=Host(`qbittorrent.${DOMAIN}`)
      - traefik.http.routers.qbittorrent-secure.tls=true
      - traefik.http.services.qbittorrent-service.loadbalancer.server.port=${QBITTORRENT_PORT_INT}
      # flame labels
      - flame.type=app
      - flame.name=qbittorrent
      - flame.url=https://qbittorrent.${DOMAIN}/
      - flame.icon=download
  sabnzbd:
    container_name: sabnzbd
    image: lscr.io/linuxserver/sabnzbd:latest
    restart: unless-stopped
    network_mode: container:gluetun
    volumes:
      - /config/sabnzbd:/config
      - /libraries/downloads/usenet:/usenet
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - SABNZBD_HOST=https://sabnzbd.${DOMAIN}/
      - SABNZBD_PORT=${SABNZBD_PORT_INT}
    labels:
      # traefik labels
      - traefik.enable=true
      - traefik.http.routers.sabnzbd.entrypoints=web
      - traefik.http.routers.sabnzbd.rule=Host(`sabnzbd.${DOMAIN}`)
      - traefik.http.middlewares.sabnzbd-redirect.redirectscheme.scheme=https
      - traefik.http.routers.sabnzbd.middlewares=sabnzbd-redirect
      - traefik.http.routers.sabnzbd-secure.entrypoints=websecure
      - traefik.http.routers.sabnzbd-secure.rule=Host(`sabnzbd.${DOMAIN}`)
      - traefik.http.routers.sabnzbd-secure.tls=true
      - traefik.http.services.sabnzbd-service.loadbalancer.server.port=${SABNZBD_PORT_INT}
      # flame labels
      - flame.type=app
      - flame.name=sabnzbd
      - flame.url=https://sabnzbd.${DOMAIN}/
      - flame.icon=target