services:

################################################################################
##### recyclarr
################################################################################

  recyclarr:
    container_name: recyclarr
    image: ghcr.io/recyclarr/recyclarr:latest
    pull_policy: always
    restart: unless-stopped
    network_mode: container:gluetun
    volumes:
      - /config/recyclarr:/config
    environment:
      # ct envvars
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      # recyclarr envvars

################################################################################
##### unpackerr
################################################################################

  unpackerr:
    container_name: unpackerr
    image: ghcr.io/hotio/unpackerr:latest
    pull_policy: always
    restart: unless-stopped
    network_mode: container:gluetun
    volumes:
      - /config/unpackerr:/config
      - /libraries/downloads:/downloads
    environment:
      # ct envvars
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      # unpackerr envvars
