services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun:latest
    restart: unless-stopped
    networks:
      - arr
    ports:
      ### apps
      # bazarr ports
      - ${BAZARR_PORT_EXT}:${BAZARR_PORT_INT}
      # lidarr ports
      - ${LIDARR_PORT_EXT}:${LIDARR_PORT_INT}
      # prowlarr ports
      - ${PROWLARR_PORT_EXT}:${PROWLARR_PORT_INT}
      # radarr ports
      - ${RADARR_PORT_EXT}:${RADARR_PORT_INT}
      # readarr ports
      - ${READARR_PORT_EXT}:${READARR_PORT_INT} 
      # sonarr ports
      - ${SONARR-1080_PORT_EXT}:${SONARR-1080_PORT_INT}
      - ${SONARR-2160_PORT_EXT}:${SONARR-2160_PORT_INT}
      - ${SONARR-ANIME_PORT_EXT}:${SONARR-ANIME_PORT_INT}
      ### clients
      # qbittorrent ports
      - ${QBITTORRENT_PORT_EXT}:${QBITTORRENT_PORT_INT}
      - ${QBITTORRENT_PORT_2_EXT}:${QBITTORRENT_PORT_2_INT}
      - ${QBITTORRENT_PORT_2_EXT}:${QBITTORRENT_PORT_2_INT}/udp
      # sabnzbd ports
      - ${SABNZBD_PORT_EXT}:${SABNZBD_PORT_INT}
      ### requesters
      # jellyseerr ports
      - ${JELLYSEERR_PORT_EXT}:${JELLYSEERR_PORT_INT}
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /config/gluetun:/gluetun
    environment:
      - SERVER_CITIES=${SERVER_CITIES}
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - UPDATER_PERIOD=6h
networks:
  arr:
    name: arr
    external: true