services:
  infisical-db:
    container_name: infisical-db
    image: postgres:14-alpine
    pull_policy: always
    restart: unless-stopped
    volumes:
      - infisical_db:/var/lib/postgresql/data
    networks:
      - main
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  infisical-redis:
    container_name: infisical-redis
    image: redis
    pull_policy: always
    restart: unless-stopped
    volumes:
      - infisical_redis:/data
    networks:
      - main
    ports:
      - ${REDIS_PORT_EXT}:${REDIS_PORT_INT}
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  infisical-db-migration:
    container_name: infisical-db-migration
    image: infisical/infisical:latest-postgres
    pull_policy: always
    restart: unless-stopped
    depends_on:
      - infisical-db
    networks:
      - main
    command: npm run migration:latest

  infisical:
    container_name: infisical
    image: infisical/infisical:latest-postgres
    pull_policy: always
    restart: unless-stopped
    depends_on:
      - infisical-db
      - infisical-redis
      - infisical-db-migration
    networks:
      - main
    ports:
      - ${INFISICAL_PORT_EXT}:${INFISICAL_PORT_INT}
    environment:
      - NODE_ENV=production
    labels:
      # traefik labels
      - traefik.enable=true
      - traefik.http.routers.infisical.entrypoints=web
      - traefik.http.routers.infisical.rule=Host(`infisical.${DOMAIN}`)
      - traefik.http.middlewares.infisical-redirect.redirectscheme.scheme=https
      - traefik.http.routers.infisical.middlewares=infisical-redirect
      - traefik.http.routers.infisical-secure.entrypoints=websecure
      - traefik.http.routers.infisical-secure.rule=Host(`infisical.${DOMAIN}`)
      - traefik.http.routers.infisical-secure.tls=true
      - traefik.http.services.infisical-service.loadbalancer.server.port=${INFISICAL_PORT_INT}
      # flame labels
      - flame.type=app
      - flame.name=infisical
      - flame.url=https://infisical.${DOMAIN}/
      - flame.icon=lock

volumes:
  infisical_db:
    driver: local
  infisical_redis:
    driver: local

networks:
  main:
    name: main
    external: true
