services:
  postgres-infisical:
    container_name: postgres-infisical
    image: postgres:14-alpine
    pull_policy: always
    restart: unless-stopped
    volumes:
      - postgres_infisical:/var/lib/postgresql/data
    networks:
      - main
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: "pg_isready --username=${POSTGRES_USER} && psql --username=${POSTGRES_USER} --list"
      interval: 5s
      timeout: 10s
      retries: 10

  redis-infisical:
    container_name: redis-infisical
    image: redis
    pull_policy: always
    restart: unless-stopped
    volumes:
      - redis_infisical:/data
    networks:
      - main
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  infisical-migration:
    container_name: infisical-migration
    image: infisical/infisical:latest-postgres
    pull_policy: always
    restart: unless-stopped
    depends_on:
      postgres-infisical:
        condition: service_healthy
    networks:
      - main
    environment:
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - AUTH_SECRET=${AUTH_SECRET}
      - DB_CONNECTION_URI=${DB_CONNECTION_URI}
      - REDIS_URL=${REDIS_URL}
      - SITE_URL=${SITE_URL}
    command: npm run migration:latest

  infisical:
    container_name: infisical
    image: infisical/infisical:latest-postgres
    pull_policy: always
    restart: unless-stopped
    depends_on:
      postgres-infisical:
        condition: service_healthy
      redis-infisical:
        condition: service_started
      infisical-migration:
        condition: service_completed_successfully
    networks:
      - main
    ports:
      - ${INFISICAL_PORT_EXT}:${INFISICAL_PORT_INT}
    environment:
      - NODE_ENV=production
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - AUTH_SECRET=${AUTH_SECRET}
      - DB_CONNECTION_URI=${DB_CONNECTION_URI}
      - REDIS_URL=${REDIS_URL}
      - SITE_URL=${SITE_URL}
    labels:
      # traefik labels
      - traefik.enable=true
      - traefik.http.routers.infisical.entrypoints=web
      - traefik.http.routers.infisical.rule=Host(`infisical.${DOMAIN}`)
      - traefik.http.middlewares.infisical-redirect.redirectscheme.scheme=https
      - traefik.http.routers.infisical.middlewares=infisical-redirect
      - traefik.http.routers.infisical-secure.entrypoints=websecure
      - traefik.http.routers.infisical-secure.rule=Host(`infisical.${DOMAIN}`)
      - traefik.http.routers.infisical-secure.tls=true
      - traefik.http.services.infisical-service.loadbalancer.server.port=${INFISICAL_PORT_INT}
      # flame labels
      - flame.type=app
      - flame.name=infisical
      - flame.url=https://infisical.${DOMAIN}/
      - flame.icon=lock

volumes:
  postgres_infisical:
    driver: local
  redis_infisical:
    driver: local

networks:
  main:
    name: main
    external: true
